// testing response object
var apiResponse = {
    "latitude": 37.8267,
    "longitude": -122.423,
    "timezone": "America/Los_Angeles",
    "offset": -7,
    "currently": {
        "time": 1444236096,
        "summary": "Mostly Cloudy",
        "icon": "partly-cloudy-day",
        "nearestStormDistance": 333,
        "nearestStormBearing": 337,
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 16.13,
        "apparentTemperature": 16.13,
        "dewPoint": 13.05,
        "humidity": 0.82,
        "windSpeed": 0.97,
        "windBearing": 254,
        "visibility": 11.64,
        "cloudCover": 0.81,
        "pressure": 1020.66,
        "ozone": 268.77
    },
    "minutely": {
        "summary": "Mostly cloudy for the hour.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1444236060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236180,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236240,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236660,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236720,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236780,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236840,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236900,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444236960,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237020,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237080,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237140,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237200,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237260,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444237980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238280,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238340,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238400,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238460,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238520,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238580,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238640,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238700,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238760,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238820,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238880,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444238940,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239000,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239180,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239240,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1444239660,
                "precipIntensity": 0,
                "precipProbability": 0
            }
        ]
    },
    "hourly": {
        "summary": "Mostly cloudy throughout the day.",
        "icon": "partly-cloudy-night",
        "data": [
            {
                "time": 1444233600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 15.46,
                "apparentTemperature": 15.46,
                "dewPoint": 13.18,
                "humidity": 0.86,
                "windSpeed": 0.45,
                "windBearing": 340,
                "visibility": 10.33,
                "cloudCover": 0.85,
                "pressure": 1020.55,
                "ozone": 269.41
            },
            {
                "time": 1444237200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 16.43,
                "apparentTemperature": 16.43,
                "dewPoint": 12.98,
                "humidity": 0.8,
                "windSpeed": 1.38,
                "windBearing": 245,
                "visibility": 12.2,
                "cloudCover": 0.79,
                "pressure": 1020.7,
                "ozone": 268.48
            },
            {
                "time": 1444240800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.72,
                "apparentTemperature": 17.72,
                "dewPoint": 13.23,
                "humidity": 0.75,
                "windSpeed": 3.94,
                "windBearing": 270,
                "visibility": 13.86,
                "cloudCover": 0.73,
                "pressure": 1020.77,
                "ozone": 267.72
            },
            {
                "time": 1444244400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 18.74,
                "apparentTemperature": 18.74,
                "dewPoint": 13.41,
                "humidity": 0.71,
                "windSpeed": 7.44,
                "windBearing": 274,
                "visibility": 14.31,
                "cloudCover": 0.66,
                "pressure": 1020.73,
                "ozone": 267.41
            },
            {
                "time": 1444248000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 19.75,
                "apparentTemperature": 19.75,
                "dewPoint": 13.51,
                "humidity": 0.67,
                "windSpeed": 10.86,
                "windBearing": 277,
                "visibility": 14.4,
                "cloudCover": 0.6,
                "pressure": 1020.58,
                "ozone": 267.26
            },
            {
                "time": 1444251600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 20.26,
                "apparentTemperature": 20.26,
                "dewPoint": 13.51,
                "humidity": 0.65,
                "windSpeed": 13.24,
                "windBearing": 279,
                "visibility": 14.24,
                "cloudCover": 0.46,
                "pressure": 1020.37,
                "ozone": 266.78
            },
            {
                "time": 1444255200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 20.68,
                "apparentTemperature": 20.68,
                "dewPoint": 13.73,
                "humidity": 0.64,
                "windSpeed": 16.62,
                "windBearing": 284,
                "visibility": 13.99,
                "cloudCover": 0.45,
                "pressure": 1020.04,
                "ozone": 265.65
            },
            {
                "time": 1444258800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 20.03,
                "apparentTemperature": 20.03,
                "dewPoint": 13.38,
                "humidity": 0.66,
                "windSpeed": 16.82,
                "windBearing": 287,
                "visibility": 14.37,
                "cloudCover": 0.42,
                "pressure": 1019.65,
                "ozone": 264.17
            },
            {
                "time": 1444262400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 19.32,
                "apparentTemperature": 19.32,
                "dewPoint": 13.21,
                "humidity": 0.68,
                "windSpeed": 16.42,
                "windBearing": 287,
                "visibility": 14.48,
                "cloudCover": 0.39,
                "pressure": 1019.41,
                "ozone": 262.75
            },
            {
                "time": 1444266000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 18.08,
                "apparentTemperature": 18.08,
                "dewPoint": 12.88,
                "humidity": 0.72,
                "windSpeed": 16.32,
                "windBearing": 287,
                "visibility": 13.87,
                "cloudCover": 0.49,
                "pressure": 1019.46,
                "ozone": 261.48
            },
            {
                "time": 1444269600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 16.69,
                "apparentTemperature": 16.69,
                "dewPoint": 12.74,
                "humidity": 0.77,
                "windSpeed": 14.93,
                "windBearing": 287,
                "visibility": 12.65,
                "cloudCover": 0.46,
                "pressure": 1019.67,
                "ozone": 260.27
            },
            {
                "time": 1444273200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 15.72,
                "apparentTemperature": 15.72,
                "dewPoint": 12.53,
                "humidity": 0.81,
                "windSpeed": 12.28,
                "windBearing": 285,
                "visibility": 11.7,
                "cloudCover": 0.38,
                "pressure": 1019.86,
                "ozone": 259.2
            },
            {
                "time": 1444276800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 15.22,
                "apparentTemperature": 15.22,
                "dewPoint": 12.45,
                "humidity": 0.84,
                "windSpeed": 10.41,
                "windBearing": 281,
                "visibility": 11.54,
                "cloudCover": 0.51,
                "pressure": 1019.96,
                "ozone": 258.34
            },
            {
                "time": 1444280400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.98,
                "apparentTemperature": 14.98,
                "dewPoint": 12.38,
                "humidity": 0.84,
                "windSpeed": 10.28,
                "windBearing": 277,
                "visibility": 11.83,
                "cloudCover": 0.47,
                "pressure": 1020,
                "ozone": 257.61
            },
            {
                "time": 1444284000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.78,
                "apparentTemperature": 14.78,
                "dewPoint": 12.48,
                "humidity": 0.86,
                "windSpeed": 10.27,
                "windBearing": 280,
                "visibility": 11.56,
                "cloudCover": 0.47,
                "pressure": 1019.99,
                "ozone": 256.94
            },
            {
                "time": 1444287600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.55,
                "apparentTemperature": 14.55,
                "dewPoint": 12.28,
                "humidity": 0.86,
                "windSpeed": 9.74,
                "windBearing": 277,
                "visibility": 12.05,
                "cloudCover": 0.48,
                "pressure": 1019.93,
                "ozone": 256.37
            },
            {
                "time": 1444291200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.36,
                "apparentTemperature": 14.36,
                "dewPoint": 12.17,
                "humidity": 0.87,
                "windSpeed": 9.59,
                "windBearing": 277,
                "visibility": 12.3,
                "cloudCover": 0.58,
                "pressure": 1019.82,
                "ozone": 255.85
            },
            {
                "time": 1444294800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 13.3,
                "apparentTemperature": 13.3,
                "dewPoint": 11.18,
                "humidity": 0.87,
                "windSpeed": 9.5,
                "windBearing": 278,
                "visibility": 12.6,
                "cloudCover": 0.6,
                "pressure": 1019.68,
                "ozone": 255.23
            },
            {
                "time": 1444298400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 13.64,
                "apparentTemperature": 13.64,
                "dewPoint": 11.73,
                "humidity": 0.88,
                "windSpeed": 8.5,
                "windBearing": 273,
                "visibility": 13.45,
                "cloudCover": 0.59,
                "pressure": 1019.49,
                "ozone": 254.43
            },
            {
                "time": 1444302000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.03,
                "apparentTemperature": 14.03,
                "dewPoint": 12.06,
                "humidity": 0.88,
                "windSpeed": 7.84,
                "windBearing": 269,
                "visibility": 14.34,
                "cloudCover": 0.57,
                "pressure": 1019.3,
                "ozone": 253.53
            },
            {
                "time": 1444305600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.23,
                "apparentTemperature": 14.23,
                "dewPoint": 12.38,
                "humidity": 0.89,
                "windSpeed": 7.44,
                "windBearing": 269,
                "visibility": 15.05,
                "cloudCover": 0.56,
                "pressure": 1019.21,
                "ozone": 252.57
            },
            {
                "time": 1444309200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.53,
                "apparentTemperature": 14.53,
                "dewPoint": 12.57,
                "humidity": 0.88,
                "windSpeed": 7.11,
                "windBearing": 273,
                "visibility": 15.51,
                "cloudCover": 0.72,
                "pressure": 1019.26,
                "ozone": 251.51
            },
            {
                "time": 1444312800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.78,
                "apparentTemperature": 14.78,
                "dewPoint": 12.74,
                "humidity": 0.88,
                "windSpeed": 6.28,
                "windBearing": 280,
                "visibility": 16.09,
                "cloudCover": 0.89,
                "pressure": 1019.4,
                "ozone": 250.4
            },
            {
                "time": 1444316400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 15.08,
                "apparentTemperature": 15.08,
                "dewPoint": 12.77,
                "humidity": 0.86,
                "windSpeed": 6.24,
                "windBearing": 284,
                "visibility": 16.09,
                "cloudCover": 0.96,
                "pressure": 1019.58,
                "ozone": 249.42
            },
            {
                "time": 1444320000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 16.18,
                "apparentTemperature": 16.18,
                "dewPoint": 12.79,
                "humidity": 0.8,
                "windSpeed": 6.32,
                "windBearing": 284,
                "visibility": 16.09,
                "cloudCover": 0.94,
                "pressure": 1019.8,
                "ozone": 248.71
            },
            {
                "time": 1444323600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.12,
                "apparentTemperature": 17.12,
                "dewPoint": 12.83,
                "humidity": 0.76,
                "windSpeed": 6.63,
                "windBearing": 283,
                "visibility": 16.09,
                "cloudCover": 0.87,
                "pressure": 1020.03,
                "ozone": 248.13
            },
            {
                "time": 1444327200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 18.19,
                "apparentTemperature": 18.19,
                "dewPoint": 12.77,
                "humidity": 0.71,
                "windSpeed": 7.35,
                "windBearing": 278,
                "visibility": 16.09,
                "cloudCover": 0.81,
                "pressure": 1020.13,
                "ozone": 247.47
            },
            {
                "time": 1444330800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 19.51,
                "apparentTemperature": 19.51,
                "dewPoint": 13.06,
                "humidity": 0.66,
                "windSpeed": 8.98,
                "windBearing": 274,
                "visibility": 16.09,
                "cloudCover": 0.82,
                "pressure": 1019.98,
                "ozone": 246.54
            },
            {
                "time": 1444334400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 20.89,
                "apparentTemperature": 20.89,
                "dewPoint": 13.52,
                "humidity": 0.63,
                "windSpeed": 11.17,
                "windBearing": 272,
                "visibility": 16.09,
                "cloudCover": 0.87,
                "pressure": 1019.68,
                "ozone": 245.53
            },
            {
                "time": 1444338000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 22.14,
                "apparentTemperature": 22.14,
                "dewPoint": 14.02,
                "humidity": 0.6,
                "windSpeed": 13,
                "windBearing": 271,
                "visibility": 16.09,
                "cloudCover": 0.92,
                "pressure": 1019.31,
                "ozone": 244.72
            },
            {
                "time": 1444341600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 22.59,
                "apparentTemperature": 22.59,
                "dewPoint": 14.31,
                "humidity": 0.6,
                "windSpeed": 13.99,
                "windBearing": 273,
                "visibility": 16.09,
                "cloudCover": 0.96,
                "pressure": 1018.86,
                "ozone": 244.31
            },
            {
                "time": 1444345200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 22.09,
                "apparentTemperature": 22.09,
                "dewPoint": 14.03,
                "humidity": 0.6,
                "windSpeed": 14.39,
                "windBearing": 276,
                "visibility": 16.09,
                "cloudCover": 0.99,
                "pressure": 1018.39,
                "ozone": 244.12
            },
            {
                "time": 1444348800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 21.24,
                "apparentTemperature": 21.24,
                "dewPoint": 13.73,
                "humidity": 0.62,
                "windSpeed": 14.23,
                "windBearing": 279,
                "visibility": 16.09,
                "cloudCover": 0.98,
                "pressure": 1018.06,
                "ozone": 243.89
            },
            {
                "time": 1444352400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 19.99,
                "apparentTemperature": 19.99,
                "dewPoint": 13.43,
                "humidity": 0.66,
                "windSpeed": 13.18,
                "windBearing": 281,
                "visibility": 16.09,
                "cloudCover": 0.92,
                "pressure": 1017.94,
                "ozone": 243.52
            },
            {
                "time": 1444356000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 18.43,
                "apparentTemperature": 18.43,
                "dewPoint": 13.04,
                "humidity": 0.71,
                "windSpeed": 11.68,
                "windBearing": 282,
                "visibility": 16.09,
                "cloudCover": 0.83,
                "pressure": 1017.94,
                "ozone": 243.11
            },
            {
                "time": 1444359600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.14,
                "apparentTemperature": 17.14,
                "dewPoint": 12.69,
                "humidity": 0.75,
                "windSpeed": 10.43,
                "windBearing": 283,
                "visibility": 16.09,
                "cloudCover": 0.76,
                "pressure": 1018.02,
                "ozone": 242.75
            },
            {
                "time": 1444363200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 16.41,
                "apparentTemperature": 16.41,
                "dewPoint": 12.52,
                "humidity": 0.78,
                "windSpeed": 9.61,
                "windBearing": 280,
                "visibility": 16.09,
                "cloudCover": 0.72,
                "pressure": 1018.19,
                "ozone": 242.5
            },
            {
                "time": 1444366800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 15.94,
                "apparentTemperature": 15.94,
                "dewPoint": 12.43,
                "humidity": 0.8,
                "windSpeed": 9.06,
                "windBearing": 273,
                "visibility": 16.09,
                "cloudCover": 0.7,
                "pressure": 1018.42,
                "ozone": 242.28
            },
            {
                "time": 1444370400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 15.54,
                "apparentTemperature": 15.54,
                "dewPoint": 12.4,
                "humidity": 0.82,
                "windSpeed": 9,
                "windBearing": 272,
                "visibility": 16.09,
                "cloudCover": 0.68,
                "pressure": 1018.58,
                "ozone": 242.03
            },
            {
                "time": 1444374000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 15.18,
                "apparentTemperature": 15.18,
                "dewPoint": 12.47,
                "humidity": 0.84,
                "windSpeed": 9.64,
                "windBearing": 278,
                "visibility": 16.09,
                "cloudCover": 0.69,
                "pressure": 1018.61,
                "ozone": 241.6
            },
            {
                "time": 1444377600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.87,
                "apparentTemperature": 14.87,
                "dewPoint": 12.57,
                "humidity": 0.86,
                "windSpeed": 11.12,
                "windBearing": 285,
                "visibility": 16.09,
                "cloudCover": 0.7,
                "pressure": 1018.57,
                "ozone": 241.14
            },
            {
                "time": 1444381200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.59,
                "apparentTemperature": 14.59,
                "dewPoint": 12.61,
                "humidity": 0.88,
                "windSpeed": 11.78,
                "windBearing": 288,
                "visibility": 16.09,
                "cloudCover": 0.69,
                "pressure": 1018.51,
                "ozone": 240.89
            },
            {
                "time": 1444384800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.33,
                "apparentTemperature": 14.33,
                "dewPoint": 12.52,
                "humidity": 0.89,
                "windSpeed": 10.83,
                "windBearing": 290,
                "visibility": 16.09,
                "cloudCover": 0.61,
                "pressure": 1018.42,
                "ozone": 241.05
            },
            {
                "time": 1444388400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.09,
                "apparentTemperature": 14.09,
                "dewPoint": 12.34,
                "humidity": 0.89,
                "windSpeed": 9.85,
                "windBearing": 289,
                "visibility": 16.09,
                "cloudCover": 0.51,
                "pressure": 1018.31,
                "ozone": 241.44
            },
            {
                "time": 1444392000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 13.88,
                "apparentTemperature": 13.88,
                "dewPoint": 12.13,
                "humidity": 0.89,
                "windSpeed": 8.05,
                "windBearing": 286,
                "visibility": 16.09,
                "cloudCover": 0.45,
                "pressure": 1018.26,
                "ozone": 241.8
            },
            {
                "time": 1444395600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 13.6,
                "apparentTemperature": 13.6,
                "dewPoint": 11.89,
                "humidity": 0.89,
                "windSpeed": 7.31,
                "windBearing": 276,
                "visibility": 16.09,
                "cloudCover": 0.43,
                "pressure": 1018.31,
                "ozone": 242.04
            },
            {
                "time": 1444399200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 13.4,
                "apparentTemperature": 13.4,
                "dewPoint": 11.68,
                "humidity": 0.89,
                "windSpeed": 7.35,
                "windBearing": 265,
                "visibility": 16.09,
                "cloudCover": 0.41,
                "pressure": 1018.41,
                "ozone": 242.24
            },
            {
                "time": 1444402800,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 14.14,
                "apparentTemperature": 14.14,
                "dewPoint": 12.04,
                "humidity": 0.87,
                "windSpeed": 7.76,
                "windBearing": 262,
                "visibility": 16.09,
                "cloudCover": 0.38,
                "pressure": 1018.54,
                "ozone": 242.4
            },
            {
                "time": 1444406400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 15.56,
                "apparentTemperature": 15.56,
                "dewPoint": 12.42,
                "humidity": 0.82,
                "windSpeed": 8.61,
                "windBearing": 268,
                "visibility": 16.09,
                "cloudCover": 0.35,
                "pressure": 1018.75,
                "ozone": 242.49
            }
        ]
    },
    "daily": {
        "summary": "No precipitation throughout the week, with temperatures rising to 24°C on Friday.",
        "icon": "clear-day",
        "data": [
            {
                "time": 1444201200,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1444227099,
                "sunsetTime": 1444268745,
                "moonPhase": 0.84,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 14.78,
                "temperatureMinTime": 1444284000,
                "temperatureMax": 20.68,
                "temperatureMaxTime": 1444255200,
                "apparentTemperatureMin": 14.78,
                "apparentTemperatureMinTime": 1444284000,
                "apparentTemperatureMax": 20.68,
                "apparentTemperatureMaxTime": 1444255200,
                "dewPoint": 13.22,
                "humidity": 0.8,
                "windSpeed": 8.58,
                "windBearing": 280,
                "visibility": 12.28,
                "cloudCover": 0.5,
                "pressure": 1019.95,
                "ozone": 267.24
            },
            {
                "time": 1444287600,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1444313554,
                "sunsetTime": 1444355055,
                "moonPhase": 0.87,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 13.3,
                "temperatureMinTime": 1444294800,
                "temperatureMax": 22.59,
                "temperatureMaxTime": 1444341600,
                "apparentTemperatureMin": 13.3,
                "apparentTemperatureMinTime": 1444294800,
                "apparentTemperatureMax": 22.59,
                "apparentTemperatureMaxTime": 1444341600,
                "dewPoint": 12.81,
                "humidity": 0.76,
                "windSpeed": 9.61,
                "windBearing": 277,
                "visibility": 15.37,
                "cloudCover": 0.78,
                "pressure": 1019.13,
                "ozone": 247.87
            },
            {
                "time": 1444374000,
                "summary": "Partly cloudy in the morning.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1444400009,
                "sunsetTime": 1444441367,
                "moonPhase": 0.9,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 13.4,
                "temperatureMinTime": 1444399200,
                "temperatureMax": 24.23,
                "temperatureMaxTime": 1444431600,
                "apparentTemperatureMin": 13.4,
                "apparentTemperatureMinTime": 1444399200,
                "apparentTemperatureMax": 24.23,
                "apparentTemperatureMaxTime": 1444431600,
                "dewPoint": 13.28,
                "humidity": 0.76,
                "windSpeed": 10.9,
                "windBearing": 279,
                "visibility": 16.09,
                "cloudCover": 0.26,
                "pressure": 1017.9,
                "ozone": 241.68
            },
            {
                "time": 1444460400,
                "summary": "Foggy in the morning.",
                "icon": "fog",
                "sunriseTime": 1444486464,
                "sunsetTime": 1444527678,
                "moonPhase": 0.93,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 15.28,
                "temperatureMinTime": 1444485600,
                "temperatureMax": 23.94,
                "temperatureMaxTime": 1444510800,
                "apparentTemperatureMin": 15.28,
                "apparentTemperatureMinTime": 1444485600,
                "apparentTemperatureMax": 23.94,
                "apparentTemperatureMaxTime": 1444510800,
                "dewPoint": 15.64,
                "humidity": 0.85,
                "windSpeed": 8.9,
                "windBearing": 256,
                "visibility": 9.75,
                "cloudCover": 0.41,
                "pressure": 1016.6,
                "ozone": 249.66
            },
            {
                "time": 1444546800,
                "summary": "Partly cloudy overnight.",
                "icon": "partly-cloudy-night",
                "sunriseTime": 1444572919,
                "sunsetTime": 1444613991,
                "moonPhase": 0.96,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 15.89,
                "temperatureMinTime": 1444572000,
                "temperatureMax": 22.29,
                "temperatureMaxTime": 1444600800,
                "apparentTemperatureMin": 15.89,
                "apparentTemperatureMinTime": 1444572000,
                "apparentTemperatureMax": 22.29,
                "apparentTemperatureMaxTime": 1444600800,
                "dewPoint": 13.72,
                "humidity": 0.77,
                "windSpeed": 6.13,
                "windBearing": 251,
                "cloudCover": 0.03,
                "pressure": 1015.57,
                "ozone": 262.21
            },
            {
                "time": 1444633200,
                "summary": "Partly cloudy in the morning.",
                "icon": "partly-cloudy-night",
                "sunriseTime": 1444659375,
                "sunsetTime": 1444700304,
                "moonPhase": 0.99,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 15.04,
                "temperatureMinTime": 1444651200,
                "temperatureMax": 21.33,
                "temperatureMaxTime": 1444687200,
                "apparentTemperatureMin": 15.04,
                "apparentTemperatureMinTime": 1444651200,
                "apparentTemperatureMax": 21.33,
                "apparentTemperatureMaxTime": 1444687200,
                "dewPoint": 12.39,
                "humidity": 0.74,
                "windSpeed": 5.47,
                "windBearing": 254,
                "cloudCover": 0.11,
                "pressure": 1016.13,
                "ozone": 265.43
            },
            {
                "time": 1444719600,
                "summary": "Partly cloudy starting in the afternoon, continuing until evening.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1444745831,
                "sunsetTime": 1444786618,
                "moonPhase": 0.02,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 15.47,
                "temperatureMinTime": 1444734000,
                "temperatureMax": 23.63,
                "temperatureMaxTime": 1444770000,
                "apparentTemperatureMin": 15.47,
                "apparentTemperatureMinTime": 1444734000,
                "apparentTemperatureMax": 23.63,
                "apparentTemperatureMaxTime": 1444770000,
                "dewPoint": 11.02,
                "humidity": 0.62,
                "windSpeed": 1.98,
                "windBearing": 284,
                "cloudCover": 0.16,
                "pressure": 1016.23,
                "ozone": 267.25
            },
            {
                "time": 1444806000,
                "summary": "Partly cloudy until afternoon.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1444832288,
                "sunsetTime": 1444872933,
                "moonPhase": 0.05,
                "precipIntensity": 0,
                "precipIntensityMax": 0,
                "precipProbability": 0,
                "temperatureMin": 17.67,
                "temperatureMinTime": 1444824000,
                "temperatureMax": 22.14,
                "temperatureMaxTime": 1444849200,
                "apparentTemperatureMin": 17.67,
                "apparentTemperatureMinTime": 1444824000,
                "apparentTemperatureMax": 22.14,
                "apparentTemperatureMaxTime": 1444849200,
                "dewPoint": 10.42,
                "humidity": 0.57,
                "windSpeed": 5.66,
                "windBearing": 244,
                "cloudCover": 0.22,
                "pressure": 1014.5,
                "ozone": 272.86
            }
        ]
    },
    "flags": {
        "sources": [
            "nwspa",
            "isd",
            "nearest-precip",
            "fnmoc",
            "sref",
            "rtma",
            "rap",
            "nam",
            "cmc",
            "gfs",
            "madis",
            "lamp",
            "darksky"
        ],
        "isd-stations": [
            "724943-99999",
            "745039-99999",
            "745065-99999",
            "994016-99999",
            "999999-23272"
        ],
        "madis-stations": [
            "AU915",
            "C5988",
            "C8158",
            "C9629",
            "CQ188",
            "D5422",
            "D8008",
            "E0426",
            "E6067",
            "FTPC1",
            "GGBC1",
            "OKXC1",
            "OMHC1",
            "PPXC1",
            "PXOC1",
            "SFOC1"
        ],
        "lamp-stations": [
            "KAPC",
            "KCCR",
            "KHWD",
            "KLVK",
            "KNUQ",
            "KOAK",
            "KPAO",
            "KSFO",
            "KSQL"
        ],
        "darksky-stations": [
            "KMUX"
        ],
        "units": "ca"
    }
};
